<a href="https://colab.research.google.com/github/chawlaKat/Notebook-Noodlings/blob/master/Get_Scattered.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Goal: sample .arff file -> dataframe -> altair plot

Uses files:


*   bark_to_byte.py (Bark_to_Byte notebook saved as python script; arff->pandas module)
*   sayHey.arff
*   sayNi.arff
*   sayEverything.arff
*   abstracted_algorithm_runs.arff


Things I did


*   Import other notebook as script
*   arff -> df using said module
*   create interactive graph with tooltip

Next up


*   Read about multi-indexing
*   Get Ni and Hey into same df
*   Plot them vs each other
*   Change 'title' header to a non-reserved keyword

In [0]:
pip install liac_arff

Collecting liac_arff
  Downloading https://files.pythonhosted.org/packages/e9/35/fbc9217cfa91d98888b43e1a19c03a50d716108c58494c558c65e308f372/liac-arff-2.4.0.tar.gz
Building wheels for collected packages: liac-arff
  Building wheel for liac-arff (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/d1/6a/e7/529dc54d76ecede4346164a09ae3168df358945612710f5203
Successfully built liac-arff
Installing collected packages: liac-arff
Successfully installed liac-arff-2.4.0

In [0]:
import bark_to_byte as bb
import altair as alt
from vega_datasets import data

In [0]:
knightFrame = bb.arff_to_dataframe("sayNi.arff")

knightFrame

           name  ... lifestatus
0   King_Arthur  ...      other
1  Sir_Bedevere  ...      other
2  Sir_Lancelot  ...      other
3   Sir_Galahad  ...       dead
4     Sir_Robin  ...       dead

[5 rows x 4 columns]

In [0]:
disneyFrame = bb.arff_to_dataframe("sayHey.arff")

disneyFrame

      name         title  braveryRating lifestatus
0  Aladdin    Street-Rat            9.0     living
1  Jasmine      Princess           10.0     living
2    Jafar  Royal-Physir            4.0      other
3   Sultan        Sultan            2.0     living
4      Abu        Monkey            9.0     living

Tutorial scatter plot from
https://altair-viz.github.io/gallery/scatter_tooltips.html

In [0]:

from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()

Chart({
  data:      Acceleration  Cylinders  Displacement  ...  Origin  Weight_in_lbs       Year
  0            12.0          8         307.0  ...     USA           3504 1970-01-01
  1            11.5          8         350.0  ...     USA           3693 1970-01-01
  2            11.0          8         318.0  ...     USA           3436 1970-01-01
  3            12.0          8         304.0  ...     USA           3433 1970-01-01
  4            10.5          8         302.0  ...     USA           3449 1970-01-01
  5            10.0          8         429.0  ...     USA           4341 1970-01-01
  6             9.0          8         454.0  ...     USA           4354 1970-01-01
  7             8.5          8         440.0  ...     USA           4312 1970-01-01
  8            10.0          8         455.0  ...     USA           4425 1970-01-01
  9             8.5          8         390.0  ...     USA           3850 1970-01-01
  10           17.5          4         133.0  ...  Europe           3090 1970-01-01
  11           11.5          8         350.0  ...     USA           4142 1970-01-01
  12           11.0          8         351.0  ...     USA           4034 1970-01-01
  13           10.5          8         383.0  ...     USA           4166 1970-01-01
  14           11.0          8         360.0  ...     USA           3850 1970-01-01
  15           10.0          8         383.0  ...     USA           3563 1970-01-01
  16            8.0          8         340.0  ...     USA           3609 1970-01-01
  17            8.0          8         302.0  ...     USA           3353 1970-01-01
  18            9.5          8         400.0  ...     USA           3761 1970-01-01
  19           10.0          8         455.0  ...     USA           3086 1970-01-01
  20           15.0          4         113.0  ...   Japan           2372 1970-01-01
  21           15.5          6         198.0  ...     USA           2833 1970-01-01
  22           15.5          6         199.0  ...     USA           2774 1970-01-01
  23           16.0          6         200.0  ...     USA           2587 1970-01-01
  24           14.5          4          97.0  ...   Japan           2130 1970-01-01
  25           20.5          4          97.0  ...  Europe           1835 1970-01-01
  26           17.5          4         110.0  ...  Europe           2672 1970-01-01
  27           14.5          4         107.0  ...  Europe           2430 1970-01-01
  28           17.5          4         104.0  ...  Europe           2375 1970-01-01
  29           12.5          4         121.0  ...  Europe           2234 1970-01-01
  ..            ...        ...           ...  ...     ...            ...        ...
  376          18.6          4         112.0  ...     USA           2640 1982-01-01
  377          18.0          4         112.0  ...     USA           2395 1982-01-01
  378          16.2          4         112.0  ...     USA           2575 1982-01-01
  379          16.0          4         135.0  ...     USA           2525 1982-01-01
  380          18.0          4         151.0  ...     USA           2735 1982-01-01
  381          16.4          4         140.0  ...     USA           2865 1982-01-01
  382          20.5          4         151.0  ...     USA           3035 1982-01-01
  383          15.3          4         105.0  ...  Europe           1980 1982-01-01
  384          18.2          4          91.0  ...   Japan           2025 1982-01-01
  385          17.6          4          91.0  ...   Japan           1970 1982-01-01
  386          14.7          4         105.0  ...     USA           2125 1982-01-01
  387          17.3          4          98.0  ...     USA           2125 1982-01-01
  388          14.5          4         120.0  ...   Japan           2160 1982-01-01
  389          14.5          4         107.0  ...   Japan           2205 1982-01-01
  390          16.9          4         108.0  ...   Japan           2245 1982-01-01
  391          15.0          4          91.0  ...   Japan           1965 1982-01-01
  392          15.7          4          91.0  ...   Japan           1965 1982-01-01
  393          16.2          4          91.0  ...   Japan           1995 1982-01-01
  394          16.4          6         181.0  ...     USA           2945 1982-01-01
  395          17.0          6         262.0  ...     USA           3015 1982-01-01
  396          14.5          4         156.0  ...     USA           2585 1982-01-01
  397          14.7          6         232.0  ...     USA           2835 1982-01-01
  398          13.9          4         144.0  ...   Japan           2665 1982-01-01
  399          13.0          4         135.0  ...     USA           2370 1982-01-01
  400          17.3          4         151.0  ...     USA           2950 1982-01-01
  401          15.6          4         140.0  ...     USA           2790 1982-01-01
  402          24.6          4          97.0  ...  Europe           2130 1982-01-01
  403          11.6          4         135.0  ...     USA           2295 1982-01-01
  404          18.6          4         120.0  ...     USA           2625 1982-01-01
  405          19.4          4         119.0  ...     USA           2720 1982-01-01

  [406 rows x 9 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'Origin'
    }),
    tooltip: [Tooltip({
      shorthand: 'Name'
    }), Tooltip({
      shorthand: 'Origin'
    }), Tooltip({
      shorthand: 'Horsepower'
    }), Tooltip({
      shorthand: 'Miles_per_Gallon'
    })],
    x: X({
      shorthand: 'Horsepower'
    }),
    y: Y({
      shorthand: 'Miles_per_Gallon'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  }),
  selection: {'selector001': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
 #source

let's try my data with color and tooltips, plus interactive zooming

In [0]:
knightSource = knightFrame

alt.Chart(knightSource).mark_circle(size=60).encode(
    x='braveryRating',
    color='lifestatus',
    tooltip=['name', 'title']
).interactive()

Chart({
  data:            name  ... lifestatus
  0   King_Arthur  ...      other
  1  Sir_Bedevere  ...      other
  2  Sir_Lancelot  ...      other
  3   Sir_Galahad  ...       dead
  4     Sir_Robin  ...       dead

  [5 rows x 4 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'name'
    }), Tooltip({
      shorthand: 'title'
    })],
    x: X({
      shorthand: 'braveryRating'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  }),
  selection: {'selector002': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

can I select only some entries?

In [0]:
alt.Chart(knightSource.loc[:4]).mark_circle(size=60).encode(
    x = 'braveryRating'
)

Chart({
  data:            name  ... lifestatus
  0   King_Arthur  ...      other
  1  Sir_Bedevere  ...      other
  2  Sir_Lancelot  ...      other
  3   Sir_Galahad  ...       dead
  4     Sir_Robin  ...       dead

  [5 rows x 4 columns],
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'braveryRating'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})

In [0]:
characterSource = bb.arff_to_dataframe("sayEverything.arff")

characterSource

          movie          name  ... braveryRating  lifestatus
0  Monty_Python   King_Arthur  ...           9.0       other
1  Monty_Python  Sir_Bedevere  ...           5.0       other
2  Monty_Python  Sir_Lancelot  ...          11.0       other
3  Monty_Python   Sir_Galahad  ...           8.0        dead
4  Monty_Python     Sir_Robin  ...           1.0        dead
5       Aladdin       Aladdin  ...           9.0      living
6       Aladdin       Jasmine  ...          10.0      living
7       Aladdin         Jafar  ...           4.0       other
8       Aladdin        Sultan  ...           2.0      living
9       Aladdin           Abu  ...           9.0      living

[10 rows x 5 columns]

In [0]:
alt.Chart(characterSource).mark_circle(size=100).encode(
    x = 'braveryRating',
    color = 'movie'
)

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'movie'
    }),
    x: X({
      shorthand: 'braveryRating'
    })
  }),
  mark: MarkDef({
    size: 100,
    type: 'circle'
  })
})

In [0]:
alt.Chart(characterSource).mark_circle(size=100).encode(
    x = 'braveryRating',
    y = 'movie',
    color = 'lifestatus',
    tooltip = ['name', 'title', 'movie', 'lifestatus']
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'name'
    }), Tooltip({
      shorthand: 'title'
    }), Tooltip({
      shorthand: 'movie'
    }), Tooltip({
      shorthand: 'lifestatus'
    })],
    x: X({
      shorthand: 'braveryRating'
    }),
    y: Y({
      shorthand: 'movie'
    })
  }),
  mark: MarkDef({
    size: 100,
    type: 'circle'
  }),
  selection: {'selector007': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(characterSource).mark_circle(size=100).encode(
    x = 'movie',
    y = 'braveryRating',
    color = 'lifestatus',
    tooltip = ['name', 'title', 'movie', 'lifestatus']
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'name'
    }), Tooltip({
      shorthand: 'title'
    }), Tooltip({
      shorthand: 'movie'
    }), Tooltip({
      shorthand: 'lifestatus'
    })],
    x: X({
      shorthand: 'movie'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: MarkDef({
    size: 100,
    type: 'circle'
  }),
  selection: {'selector001': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(characterSource).mark_boxplot(extent = 'min-max').encode(
    x = 'movie',
    y = 'braveryRating',
    color = 'lifestatus',
    tooltip = ['name', 'movie', 'lifestatus']
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'name'
    }), Tooltip({
      shorthand: 'movie'
    }), Tooltip({
      shorthand: 'lifestatus'
    })],
    x: X({
      shorthand: 'movie'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  }),
  selection: {'selector003': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

boxplot altair tutorial: https://altair-viz.github.io/gallery/boxplot_max_min.html

In [0]:
source = data.population.url

alt.Chart(source).mark_boxplot(extent='min-max').encode(
    x='age:O',
    y='people:Q'
).interactive()

Chart({
  data: 'https://vega.github.io/vega-datasets/data/population.json',
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'age:O'
    }),
    y: Y({
      shorthand: 'people:Q'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  }),
  selection: {'selector007': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
source

'https://vega.github.io/vega-datasets/data/population.json'

In [0]:
alt.Chart(characterSource).mark_boxplot(extent = 'min-max').encode(
    x = 'movie',
    y = 'braveryRating'
)

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'movie'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  })
})

In [0]:
alt.Chart(characterSource).mark_boxplot(extent = 'min-max').encode(
    x = 'movie',
    y = 'braveryRating',
    color = 'lifestatus'
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    x: X({
      shorthand: 'movie'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  }),
  selection: {'selector005': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(characterSource).mark_boxplot(extent= 'min-max').encode(
    x = 'lifestatus',
    y = 'braveryRating',
    color = 'movie'
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'movie'
    }),
    x: X({
      shorthand: 'lifestatus'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  }),
  selection: {'selector006': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(characterSource).mark_boxplot(extent = 'min-max').encode(
    x = 'movie',
    y = 'braveryRating',
    color = 'lifestatus',
    tooltip = ['name']
).interactive()

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'lifestatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'name'
    })],
    x: X({
      shorthand: 'movie'
    }),
    y: Y({
      shorthand: 'braveryRating'
    })
  }),
  mark: BoxPlotDef({
    extent: 'min-max',
    type: 'boxplot'
  }),
  selection: {'selector008': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [37]:
algSource = bb.arff_to_dataframe('abstracted_algorithm_runs.arff')

algSource

   instance_id  repetition       algorithm   runtime runstatus
0   Instance_0         1.0     algorithm_0  3600.000    memout
1   Instance_0         1.0     algorithm_1  3600.000    memout
2   Instance_0         1.0  id_algorithm_0   311.863        ok
3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
4   Instance_1         1.0     algorithm_0  3600.000    memout
5   Instance_1         1.0     algorithm_1  3600.000    memout
6   Instance_1         1.0  id_algorithm_0    78.121        ok
7   Instance_1         1.0  id_algorithm_1   600.402        ok
8   Instance_2         1.0     algorithm_0  3600.000    memout
9   Instance_2         1.0     algorithm_1  3600.000    memout
10  Instance_2         1.0  id_algorithm_0     0.012        ok
11  Instance_2         1.0  id_algorithm_1    60.720        ok
12  Instance_3         1.0     algorithm_0  3600.000    memout
13  Instance_3         1.0     algorithm_1    92.986        ok
14  Instance_3         1.0  id_algorithm_0  2031.039        ok
15  Instance_3         1.0  id_algorithm_1   141.857        ok
16  Instance_4         1.0     algorithm_0  3600.000    memout
17  Instance_4         1.0     algorithm_1  3600.000    memout
18  Instance_4         1.0  id_algorithm_0   422.530        ok
19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
20  Instance_5         1.0     algorithm_0   182.019        ok
21  Instance_5         1.0     algorithm_1  3600.000    memout
22  Instance_5         1.0  id_algorithm_0    66.988        ok
23  Instance_5         1.0  id_algorithm_1   249.488        ok

In [0]:
alt.Chart(algSource).mark_boxplot().encode(
    x = 'algorithm',
    y = 'runtime'
).interactive()

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'algorithm'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: 'boxplot',
  selection: {'selector014': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(algSource).mark_boxplot().encode(
    x = 'algorithm',
    y = 'runtime',
    color = 'runstatus'
)

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'runstatus'
    }),
    x: X({
      shorthand: 'algorithm'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: 'boxplot'
})

In [0]:
alt.Chart(algSource).mark_boxplot().encode(
    x = 'runstatus',
    y = 'runtime',
    color = 'algorithm'
)

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'algorithm'
    }),
    x: X({
      shorthand: 'runstatus'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: 'boxplot'
})

In [0]:
goodRunsSource = bb.where_equals(algSource, 'runstatus', 'ok')

alt.Chart(goodRunsSource).mark_boxplot().encode(
    x = 'algorithm',
    y = 'runtime'
)

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  20  Instance_5         1.0     algorithm_0   182.019        ok
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    x: X({
      field: 'algorithm',
      type: 'nominal'
    }),
    y: Y({
      field: 'runtime',
      type: 'quantitative'
    })
  }),
  mark: 'boxplot'
})

In [0]:
alt.Chart(goodRunsSource).mark_bar().encode(
    x = 'algorithm',
    y = 'runtime',
    #tooltip=['name', 'title']

).interactive()

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  20  Instance_5         1.0     algorithm_0   182.019        ok
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    x: X({
      field: 'algorithm',
      type: 'nominal'
    }),
    y: Y({
      field: 'runtime',
      type: 'quantitative'
    })
  }),
  mark: 'bar',
  selection: {'selector002': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(algSource).mark_bar().encode(
    x = 'algorithm',
    y = 'runtime'
).interactive()

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'algorithm'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: 'bar',
  selection: {'selector016': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(algSource).mark_bar().encode(
    x = 'algorithm',
    y = 'runtime',
    color = 'runstatus'
).interactive()

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'runstatus'
    }),
    x: X({
      shorthand: 'algorithm'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: 'bar',
  selection: {'selector017': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

In [0]:
alt.Chart(algSource).mark_circle(size = 60).encode(
    x = 'algorithm',
    y = 'runtime',
    color = 'runstatus',
    tooltip = ['runtime', 'algorithm', 'instance_id', 'runstatus']
).interactive()

Chart({
  data:    instance_id  repetition       algorithm   runtime runstatus
  0   Instance_0         1.0     algorithm_0  3600.000    memout
  1   Instance_0         1.0     algorithm_1  3600.000    memout
  2   Instance_0         1.0  id_algorithm_0   311.863        ok
  3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
  4   Instance_1         1.0     algorithm_0  3600.000    memout
  5   Instance_1         1.0     algorithm_1  3600.000    memout
  6   Instance_1         1.0  id_algorithm_0    78.121        ok
  7   Instance_1         1.0  id_algorithm_1   600.402        ok
  8   Instance_2         1.0     algorithm_0  3600.000    memout
  9   Instance_2         1.0     algorithm_1  3600.000    memout
  10  Instance_2         1.0  id_algorithm_0     0.012        ok
  11  Instance_2         1.0  id_algorithm_1    60.720        ok
  12  Instance_3         1.0     algorithm_0  3600.000    memout
  13  Instance_3         1.0     algorithm_1    92.986        ok
  14  Instance_3         1.0  id_algorithm_0  2031.039        ok
  15  Instance_3         1.0  id_algorithm_1   141.857        ok
  16  Instance_4         1.0     algorithm_0  3600.000    memout
  17  Instance_4         1.0     algorithm_1  3600.000    memout
  18  Instance_4         1.0  id_algorithm_0   422.530        ok
  19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
  20  Instance_5         1.0     algorithm_0   182.019        ok
  21  Instance_5         1.0     algorithm_1  3600.000    memout
  22  Instance_5         1.0  id_algorithm_0    66.988        ok
  23  Instance_5         1.0  id_algorithm_1   249.488        ok,
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'runstatus'
    }),
    tooltip: [Tooltip({
      shorthand: 'runtime'
    }), Tooltip({
      shorthand: 'algorithm'
    }), Tooltip({
      shorthand: 'instance_id'
    }), Tooltip({
      shorthand: 'runstatus'
    })],
    x: X({
      shorthand: 'algorithm'
    }),
    y: Y({
      shorthand: 'runtime'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  }),
  selection: {'selector023': SelectionDef({
    bind: 'scales',
    encodings: ['x', 'y'],
    type: 'interval'
  })}
})

Next up (6/18/19): 

*   dynamically give file name to graph
*   successfully plot algorithm vs algorithm

graphing with multiindexing?

In [0]:
characterSource

          movie          name  ... braveryRating  lifestatus
0  Monty_Python   King_Arthur  ...           9.0       other
1  Monty_Python  Sir_Bedevere  ...           5.0       other
2  Monty_Python  Sir_Lancelot  ...          11.0       other
3  Monty_Python   Sir_Galahad  ...           8.0        dead
4  Monty_Python     Sir_Robin  ...           1.0        dead
5       Aladdin       Aladdin  ...           9.0      living
6       Aladdin       Jasmine  ...          10.0      living
7       Aladdin         Jafar  ...           4.0       other
8       Aladdin        Sultan  ...           2.0      living
9       Aladdin           Abu  ...           9.0      living

[10 rows x 5 columns]

In [0]:
cs_grouped = characterSource.groupby('movie')

cs_grouped

In [0]:
list(cs_grouped)

[('Aladdin',      movie     name         title  braveryRating lifestatus
  5  Aladdin  Aladdin    Street-Rat            9.0     living
  6  Aladdin  Jasmine      Princess           10.0     living
  7  Aladdin    Jafar  Royal-Physir            4.0      other
  8  Aladdin   Sultan        Sultan            2.0     living
  9  Aladdin      Abu        Monkey            9.0     living),
 ('Monty_Python',           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead

  [5 rows x 5 columns])]

I'm not quite sure how to graph it from here.

It looks like Altair has a built-in filter transformation, though?
https://altair-viz.github.io/user_guide/transform.html
https://altair-viz.github.io/user_guide/transform.html#user-guide-filter-transform

In [8]:
alt.Chart(cs_grouped).mark_circle(size=60).encode(
    x = 'Aladdin',
    y = 'Monty_Python'
)

/usr/local/lib/python3.6/dist-packages/altair/vegalite/v3/api.py:97: UserWarning: data of type <class 'pandas.core.groupby.generic.DataFrameGroupBy'> not recognized
  warnings.warn("data of type {} not recognized".format(type(data)))

ValueError: ignored

Chart({
  data: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fe9b7ce0dd8>,
  encoding: FacetedEncoding({
    x: X({
      shorthand: 'Aladdin'
    }),
    y: Y({
      shorthand: 'Monty_Python'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})

In [10]:
alt.Chart(characterSource).mark_circle(size=60).encode(
    x = 'braveryRating'
)

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'braveryRating',
      type: 'quantitative'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})

In [15]:
alt.Chart(characterSource).mark_circle(size=60).encode(
    x = 'braveryRating',
    color = 'movie'
).transform_filter(alt.FieldOneOfPredicate(field='movie', oneOf=['Aladdin', 'Monty_Python']))

Chart({
  data:           movie          name  ... braveryRating  lifestatus
  0  Monty_Python   King_Arthur  ...           9.0       other
  1  Monty_Python  Sir_Bedevere  ...           5.0       other
  2  Monty_Python  Sir_Lancelot  ...          11.0       other
  3  Monty_Python   Sir_Galahad  ...           8.0        dead
  4  Monty_Python     Sir_Robin  ...           1.0        dead
  5       Aladdin       Aladdin  ...           9.0      living
  6       Aladdin       Jasmine  ...          10.0      living
  7       Aladdin         Jafar  ...           4.0       other
  8       Aladdin        Sultan  ...           2.0      living
  9       Aladdin           Abu  ...           9.0      living

  [10 rows x 5 columns],
  encoding: FacetedEncoding({
    color: Color({
      field: 'movie',
      type: 'nominal'
    }),
    x: X({
      field: 'braveryRating',
      type: 'quantitative'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  }),
  transform: [FilterTransform({
    filter: FieldOneOfPredicate({
      field: 'movie',
      oneOf: ['Aladdin', 'Monty_Python']
    })
  })]
})

In [28]:
characterMulti = characterSource.set_index(['movie', 'name'])
characterMulti

                                                            title  ...  lifestatus
movie        name                                                  ...
Monty_Python King_Arthur                      King-of-the-Britons  ...       other
             Sir_Bedevere                                The-Wise  ...       other
             Sir_Lancelot                               The-Brave  ...       other
             Sir_Galahad                                 The-Pure  ...        dead
             Sir_Robin     The-Not-Quite-So-Brave-As-Sir-Lancelot  ...        dead
Aladdin      Aladdin                                   Street-Rat  ...      living
             Jasmine                                     Princess  ...      living
             Jafar                                   Royal-Physir  ...       other
             Sultan                                        Sultan  ...      living
             Abu                                           Monkey  ...      living

[10 rows x 3 columns]

In [18]:
characterMulti.unstack(level=0)

                     title  ...   lifestatus
movie              Aladdin  ... Monty_Python
name                        ...
Abu                 Monkey  ...          NaN
Aladdin         Street-Rat  ...          NaN
Jafar         Royal-Physir  ...          NaN
Jasmine           Princess  ...          NaN
King_Arthur            NaN  ...        other
Sir_Bedevere           NaN  ...        other
Sir_Galahad            NaN  ...         dead
Sir_Lancelot           NaN  ...        other
Sir_Robin              NaN  ...         dead
Sultan              Sultan  ...          NaN

[10 rows x 6 columns]

In [0]:
cm_unstacked = characterMulti.unstack(level=0)

In [20]:
alt.Chart(cm_unstacked).mark_circle(size=60).encode(
    x = ('braveryRating', 'Aladdin'),
    y = ('braveryRating', 'Monty_Python')
)

ValueError: ignored

Chart({
  data:                      title  ...   lifestatus
  movie              Aladdin  ... Monty_Python
  name                        ...
  Abu                 Monkey  ...          NaN
  Aladdin         Street-Rat  ...          NaN
  Jafar         Royal-Physir  ...          NaN
  Jasmine           Princess  ...          NaN
  King_Arthur            NaN  ...        other
  Sir_Bedevere           NaN  ...        other
  Sir_Galahad            NaN  ...         dead
  Sir_Lancelot           NaN  ...        other
  Sir_Robin              NaN  ...         dead
  Sultan              Sultan  ...          NaN

  [10 rows x 6 columns],
  encoding: FacetedEncoding({
    x: [X({
      shorthand: 'braveryRating'
    }), X({
      shorthand: 'Aladdin'
    })],
    y: [Y({
      shorthand: 'braveryRating'
    }), Y({
      shorthand: 'Monty_Python'
    })]
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})

In [21]:
cm_unstacked.columns

MultiIndex(levels=[['title', 'braveryRating', 'lifestatus'], ['Aladdin', 'Monty_Python']],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=[None, 'movie'])

In [22]:
characterMulti.unstack()

               title                            ...   lifestatus
name             Abu     Aladdin         Jafar  ... Sir_Lancelot Sir_Robin  Sultan
movie                                           ...
Aladdin       Monkey  Street-Rat  Royal-Physir  ...          NaN       NaN  living
Monty_Python     NaN         NaN           NaN  ...        other      dead     NaN

[2 rows x 30 columns]

In [29]:
characterMulti.reset_index()

          movie          name  ... braveryRating  lifestatus
0  Monty_Python   King_Arthur  ...           9.0       other
1  Monty_Python  Sir_Bedevere  ...           5.0       other
2  Monty_Python  Sir_Lancelot  ...          11.0       other
3  Monty_Python   Sir_Galahad  ...           8.0        dead
4  Monty_Python     Sir_Robin  ...           1.0        dead
5       Aladdin       Aladdin  ...           9.0      living
6       Aladdin       Jasmine  ...          10.0      living
7       Aladdin         Jafar  ...           4.0       other
8       Aladdin        Sultan  ...           2.0      living
9       Aladdin           Abu  ...           9.0      living

[10 rows x 5 columns]

In [32]:
cm_unstacked

                     title  ...   lifestatus
movie              Aladdin  ... Monty_Python
name                        ...
Abu                 Monkey  ...          NaN
Aladdin         Street-Rat  ...          NaN
Jafar         Royal-Physir  ...          NaN
Jasmine           Princess  ...          NaN
King_Arthur            NaN  ...        other
Sir_Bedevere           NaN  ...        other
Sir_Galahad            NaN  ...         dead
Sir_Lancelot           NaN  ...        other
Sir_Robin              NaN  ...         dead
Sultan              Sultan  ...          NaN

[10 rows x 6 columns]

In [33]:
cm_unstacked.columns

MultiIndex(levels=[['title', 'braveryRating', 'lifestatus'], ['Aladdin', 'Monty_Python']],
           codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=[None, 'movie'])

In [34]:
cm_unstacked.columns = ['Aladdin_title', 'Monty_Python_title', 'Aladdin_braveryRating', 'Monty_Python_braveryRating', 'Aladdin_lifestatus', 'Monty_Python_lifestatus']

cm_unstacked

             Aladdin_title  ... Monty_Python_lifestatus
name                        ...
Abu                 Monkey  ...                     NaN
Aladdin         Street-Rat  ...                     NaN
Jafar         Royal-Physir  ...                     NaN
Jasmine           Princess  ...                     NaN
King_Arthur            NaN  ...                   other
Sir_Bedevere           NaN  ...                   other
Sir_Galahad            NaN  ...                    dead
Sir_Lancelot           NaN  ...                   other
Sir_Robin              NaN  ...                    dead
Sultan              Sultan  ...                     NaN

[10 rows x 6 columns]

In [35]:
alt.Chart(cm_unstacked).mark_circle(size=60).encode(
    x = 'Aladdin_braveryRating',
    y = 'Monty_Python_braveryRating'
)

Chart({
  data:              Aladdin_title  ... Monty_Python_lifestatus
  name                        ...
  Abu                 Monkey  ...                     NaN
  Aladdin         Street-Rat  ...                     NaN
  Jafar         Royal-Physir  ...                     NaN
  Jasmine           Princess  ...                     NaN
  King_Arthur            NaN  ...                   other
  Sir_Bedevere           NaN  ...                   other
  Sir_Galahad            NaN  ...                    dead
  Sir_Lancelot           NaN  ...                   other
  Sir_Robin              NaN  ...                    dead
  Sultan              Sultan  ...                     NaN

  [10 rows x 6 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'Aladdin_braveryRating',
      type: 'quantitative'
    }),
    y: Y({
      field: 'Monty_Python_braveryRating',
      type: 'quantitative'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})

In [38]:
algSource

   instance_id  repetition       algorithm   runtime runstatus
0   Instance_0         1.0     algorithm_0  3600.000    memout
1   Instance_0         1.0     algorithm_1  3600.000    memout
2   Instance_0         1.0  id_algorithm_0   311.863        ok
3   Instance_0         1.0  id_algorithm_1  3600.000   timeout
4   Instance_1         1.0     algorithm_0  3600.000    memout
5   Instance_1         1.0     algorithm_1  3600.000    memout
6   Instance_1         1.0  id_algorithm_0    78.121        ok
7   Instance_1         1.0  id_algorithm_1   600.402        ok
8   Instance_2         1.0     algorithm_0  3600.000    memout
9   Instance_2         1.0     algorithm_1  3600.000    memout
10  Instance_2         1.0  id_algorithm_0     0.012        ok
11  Instance_2         1.0  id_algorithm_1    60.720        ok
12  Instance_3         1.0     algorithm_0  3600.000    memout
13  Instance_3         1.0     algorithm_1    92.986        ok
14  Instance_3         1.0  id_algorithm_0  2031.039        ok
15  Instance_3         1.0  id_algorithm_1   141.857        ok
16  Instance_4         1.0     algorithm_0  3600.000    memout
17  Instance_4         1.0     algorithm_1  3600.000    memout
18  Instance_4         1.0  id_algorithm_0   422.530        ok
19  Instance_4         1.0  id_algorithm_1  3600.000   timeout
20  Instance_5         1.0     algorithm_0   182.019        ok
21  Instance_5         1.0     algorithm_1  3600.000    memout
22  Instance_5         1.0  id_algorithm_0    66.988        ok
23  Instance_5         1.0  id_algorithm_1   249.488        ok

In [41]:
#algorithm source multiindexed
as_multi = algSource.set_index(['algorithm', 'instance_id'])

as_multi

                            repetition   runtime runstatus
algorithm      instance_id
algorithm_0    Instance_0          1.0  3600.000    memout
algorithm_1    Instance_0          1.0  3600.000    memout
id_algorithm_0 Instance_0          1.0   311.863        ok
id_algorithm_1 Instance_0          1.0  3600.000   timeout
algorithm_0    Instance_1          1.0  3600.000    memout
algorithm_1    Instance_1          1.0  3600.000    memout
id_algorithm_0 Instance_1          1.0    78.121        ok
id_algorithm_1 Instance_1          1.0   600.402        ok
algorithm_0    Instance_2          1.0  3600.000    memout
algorithm_1    Instance_2          1.0  3600.000    memout
id_algorithm_0 Instance_2          1.0     0.012        ok
id_algorithm_1 Instance_2          1.0    60.720        ok
algorithm_0    Instance_3          1.0  3600.000    memout
algorithm_1    Instance_3          1.0    92.986        ok
id_algorithm_0 Instance_3          1.0  2031.039        ok
id_algorithm_1 Instance_3          1.0   141.857        ok
algorithm_0    Instance_4          1.0  3600.000    memout
algorithm_1    Instance_4          1.0  3600.000    memout
id_algorithm_0 Instance_4          1.0   422.530        ok
id_algorithm_1 Instance_4          1.0  3600.000   timeout
algorithm_0    Instance_5          1.0   182.019        ok
algorithm_1    Instance_5          1.0  3600.000    memout
id_algorithm_0 Instance_5          1.0    66.988        ok
id_algorithm_1 Instance_5          1.0   249.488        ok

In [42]:
as_unstacked = as_multi.unstack(level=0)

as_unstacked

             repetition              ...      runstatus
algorithm   algorithm_0 algorithm_1  ... id_algorithm_0 id_algorithm_1
instance_id                          ...
Instance_0          1.0         1.0  ...             ok        timeout
Instance_1          1.0         1.0  ...             ok             ok
Instance_2          1.0         1.0  ...             ok             ok
Instance_3          1.0         1.0  ...             ok             ok
Instance_4          1.0         1.0  ...             ok        timeout
Instance_5          1.0         1.0  ...             ok             ok

[6 rows x 12 columns]

In [43]:
as_unstacked.columns

MultiIndex(levels=[['repetition', 'runtime', 'runstatus'], ['algorithm_0', 'algorithm_1', 'id_algorithm_0', 'id_algorithm_1']],
           codes=[[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]],
           names=[None, 'algorithm'])

In [44]:
as_unstacked.columns = ['rep_a0', 'rep_a1', 'rep_a0_id', 'rep_a1_id',
                        'runtime_a0', 'runtime_a1', 'runtime_a0_id', 'runtime_a1_id',
                        'runstat_a0', 'runstat_a1', 'runstat_a0_id', 'runstat_a1_id']

as_unstacked

             rep_a0  rep_a1  rep_a0_id  ...  runstat_a1  runstat_a0_id  runstat_a1_id
instance_id                             ...
Instance_0      1.0     1.0        1.0  ...      memout             ok        timeout
Instance_1      1.0     1.0        1.0  ...      memout             ok             ok
Instance_2      1.0     1.0        1.0  ...      memout             ok             ok
Instance_3      1.0     1.0        1.0  ...          ok             ok             ok
Instance_4      1.0     1.0        1.0  ...      memout             ok        timeout
Instance_5      1.0     1.0        1.0  ...      memout             ok             ok

[6 rows x 12 columns]

In [47]:
alt.Chart(as_unstacked).mark_circle(size=60).encode(
    x = 'runtime_a0',
    y = 'runtime_a1'
)

Chart({
  data:              rep_a0  rep_a1  rep_a0_id  ...  runstat_a1  runstat_a0_id  runstat_a1_id
  instance_id                             ...
  Instance_0      1.0     1.0        1.0  ...      memout             ok        timeout
  Instance_1      1.0     1.0        1.0  ...      memout             ok             ok
  Instance_2      1.0     1.0        1.0  ...      memout             ok             ok
  Instance_3      1.0     1.0        1.0  ...          ok             ok             ok
  Instance_4      1.0     1.0        1.0  ...      memout             ok        timeout
  Instance_5      1.0     1.0        1.0  ...      memout             ok             ok

  [6 rows x 12 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'runtime_a0',
      type: 'quantitative'
    }),
    y: Y({
      field: 'runtime_a1',
      type: 'quantitative'
    })
  }),
  mark: MarkDef({
    size: 60,
    type: 'circle'
  })
})